apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scmc-backend.fullname" . }}-secrets
  labels:
    {{- include "scmc-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  SUPABASE_JWT_SECRET: {{ .Values.secrets.SUPABASE_JWT_SECRET | b64enc | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secrets.SUPABASE_SERVICE_ROLE_KEY | b64enc | quote }}
  SUPABASE_URL: {{ .Values.secrets.SUPABASE_URL | b64enc | quote }}
